version: '3'

services:

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: run-php-app
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html/"
    networks:
      - php-mysql-networks
    depends_on:
      - php-db

  php-db:
    image: mysql:8.3.0
    container_name: run-php-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "@Fr0J4ck"
      MYSQL_DATABASE: "my_form"
      MYSQL_USER:"test"
      MYSQL_PASSWORD: "p@55w0rd"
    command: 
      - "docker exec run-php-db mysqlbinlog ./MySQL/mysql/"
    volumes:
      - "./MySQL/db:/docker-entrypoint-initdb.d"
      - "./MySQL/mysql_logs:/var/log/mysql"
    networks:
      - php-mysql-networks

  php-myadmin:
    container_name: run-php-MyAdmin
    image: phpmyadmin:apache
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - php-mysql-networks
    links:
      - php-db:db
    depends_on:
      - php-db

volumes:
  mysql-data:

networks:
  php-mysql-networks:
